name: PHPCS check

on:
  push:
    branches:
      - main
      - stage
      - develop
      - v[0-9]+.x
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

      # https://github.com/chekalsky/phpcs-action (community)
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1.2.0
        with:
          enable_warnings: true
          phpcs_bin_path: './vendor/bin/phpcs'
